# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_liwowejjIEgwBwNeqMRBeZBw_Z0pc9N
"""

# --- PROGRAMA BASE: MENÚ DEL RESTAURANTE ---
def mostrar_menu():
    print("\n--- 🍽️ MENÚ DEL RESTAURANTE COLAB ---")
    print("1. Ver Platillos Disponibles")
    print("2. Calcular Propina Sugerida")
    print("3. Personalizar Nombre del Restaurante")
    print("4. Salir")
    print("5. Calcular Total con IVA")

def ejecutar_asistente():
    restaurante_nombre = "El Buen Sabor"
    continuar = True
    while continuar:
        mostrar_menu()
        opcion = input("Seleccione una opción (1-5): ")
        if opcion == "1":
            print("🥗 Platillos disponibles: Pasta (15€), Pizza (12€), Ensalada (10€).")
        elif opcion == "2":
            try:
                cuenta_total = float(input("Ingresa el total de la cuenta para calcular la propina: "))
                propina_sugerida = cuenta_total * 0.10 # 10% de propina
                print(f"💰 La propina sugerida es de {propina_sugerida:.2f}€ (10%).")
            except ValueError:
                print("⚠️ Entrada inválida. Por favor, ingresa un número.")
        elif opcion == "3":
            nuevo_nombre = input("Ingresa el nuevo nombre de tu restaurante: ")
            restaurante_nombre = nuevo_nombre
            print(f"🍽️ Nombre actualizado: {restaurante_nombre}")
        elif opcion == "4":
            print(f"¡Gracias por visitar {restaurante_nombre}! ¡Hasta pronto!")
            continuar = False
        elif opcion == "5":
            try:
                subtotal = float(input("Ingresa el subtotal de la cuenta: "))
                iva = subtotal * 0.21 # Asumiendo un IVA del 21%
                total_con_iva = subtotal + iva
                print(f"🧾 Subtotal: {subtotal:.2f}€")
                print(f"🧾 IVA (21%): {iva:.2f}€")
                print(f"✅ Total con IVA: {total_con_iva:.2f}€")
            except ValueError:
                print("⚠️ Entrada inválida. Por favor, ingresa un número.")
        else:
            print("⚠️ Opción no válida. Intenta de nuevo.")

# Iniciar el programa
ejecutar_asistente()

# --- PROGRAMA BASE: ASISTENTE DE MISIÓN ESPACIAL ---
def mostrar_menu():
    print("\n--- 🚀 SISTEMA DE CONTROL LUNAR ---")
    print("1. Verificar niveles de oxígeno")
    print("2. Calcular distancia a la Tierra")
    print("3. Personalizar nombre de la nave")
    print("4. Salir")

def ejecutar_asistente():
    nave = "Apolo 11"
    continuar = True
    while continuar:
        mostrar_menu()
        opcion = input("Seleccione una opción (1-4): ")
        if opcion == "1":
            print("✅ Oxígeno al 98%. Todo normal.")
        elif opcion == "2":
            distancia = 384400
            print(f"📍 La distancia actual es de {distancia}km")
        elif opcion == "3":
            nuevo_nombre = input("Ingresa el nuevo nombre de tu nave: ")
            nave = nuevo_nombre
            print(f"🚀 Nombre actualizado: {nave}")
        elif opcion == "4":
            print(f"️ Cerrando conexión desde la nave {nave}. ¡Adiós!")
            continuar = False
        else:
            print("⚠️ Opción no válida. Intenta de nuevo.")

# Iniciar el programa
ejecutar_asistente()